GET http://localhost:8888/api/secureDatas
Accept: application/json

###

GET http://localhost:8888/api/getFromWiki
Accept: application/json

###

GET http://localhost:8888/api/secureDatas?page=1&limit=20
Accept: application/json

###

POST http://localhost:8888/api/secureDatas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0bGphd2hkaWxhbm13bGt

{
  "title": "Solteiras Noivas Casadas",
  "description": "This is just description",
  "image": "https://i.pinimg.com/564x/6f/0c/89/6f0c893f02634dccb513da174808694a.jpg"
}

###

DELETE http://localhost:8888/api/secureDatas/630bebe7f1a5f687242854bb
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0bGphd2hkaWxhbm13bGt

###

GET http://localhost:8888/api/searchDatas/использовать
Content-Type: application/json

###
